### ISSUE TITLE
O que estudar?

### ISSUE THREAD

**Issue by notnotgabriel** [FRONTEND-CPS/meetups#14]
O que um front-end precisa estudar nos dias de hoje?

**Comment by notnotgabriel** [comment]
Discutido no meetup 4.
bced184d8a585b1b721f1c8e64f434e22a2dc132

**Comment by victorperin** [comment]
VOLTA! O.O

**Comment by notnotgabriel** [comment]
VOLTA! O.O (Willian Martins sobre trancar a faculdade).
uhauhauhauha
